### ISSUE TITLE
dags folder files can't be seen

### ISSUE THREAD

**Issue by tosolveit** [kjam/data-pipelines-course#1]
Hi, I am new to this subject and I'm following the course on safari, I installed airflow on my local machine and a remote server, on both cases I can't see my files after $airflow list_dags command, I exported the path for AIRFLOW_HOME , there is a dag folder in the airflow home directory, what is point that I'm missing? Also web UI doesn't show the files too, web server is printing "Filling up the DagBag from /Users/myuser_name/airflow/dags" but doesn't let me see the dags.

note: I didn't use the requirements.txt in the virtualenv, I just followed what you've done in the videos.

Update: $airflow list_dags works now , It was my fault that I used a same dag_id with the examples, unfortunately interface still does not update.

Update2: Now I can see the dag, it took a while to show that but on/off button is invisible for my dag.

**Comment by kjam** [comment]
Hi @tosolveit ,

Sorry for my late response!! I'm glad you were able to get it working. What fixed it (for others who might find the issue?). For me, I have my path set to the root airflow folder, which has a folder named `dags` in it. Did you restart the webserver to see the new dags or did they just get added with a refresh?

Thanks again and sorry for my delay. 
-katharine

**Comment by tosolveit** [comment]
Hi kjam,
I think the problem is related to the error below.
https://issues.apache.org/jira/browse/AIRFLOW-276

I tried in many different ec2 instances, starting from scratch and following the installation steps, GUI does not update even I start the web server again. I will try using previous versions of airflow.

On the other hand, naming the dags are important. If you use the same dag name in multiple .py files even you have different purpose for each .py file, those tags are gonna be listed only once by the  `airflow list_dags ` command, I solved that mistake by renaming the dag, as I said before I can't see any dag that I've created on GUI.

**Comment by kjam** [comment]
Excellent, well I'm glad it worked out! I'll mark this issue as closed -- but feel free to reach out if you have any other issues. Happy Pythoning! :smile:

**Comment by joaoferrao** [comment]
Hey @kjam, I'm having a somewhat similar issue. This is what I did:

Set the example files to False in the .cfg file and created your tutorial DAG in the /dag folder
`export AIRFLOW_HOME=$(pwd)` --> since I'm in the folder where I want it to be
`airflow initdb`
`airflow web server -p 8080`

Two issues:
- Running `airflow list_dags` only shows the examples... I have even tried `airflow resetdb` but it still won't work... :(
- In the web server I can see my DAG but I also see the examples.. any idea why?

### After some closer inspection...
It seems as though the env variable we create initially ($AIRFLOW_HOME) gets lots somewhere along the way and upon one of my initdb / resetdb, it started using the default directory ~/airflow and it was fetching the settings from that place instead.

**Comment by sahilngi** [comment]
Hey @joaoferrao , I didn't got how you solved it properly, Could u please explain a bit in detail as I'm new to docker and Virtual enviroments. 

I'm also facing the similar problem where i'm getting only the examples when I'm running 'airflow list_dags' command. 

My goal is to see all the dags which are in my dag folder directly to the homepage of Airflow Home. Currently, it is showing as no results.
